name: main
on:
  push:
    branches: [ main ]
jobs:
  update:
    runs-on: self-hosted
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: git
        run: cd /mnt/data/BeetiWepApp-main && git pull && docker exec BeetiWepApp-main_web_1 /var/www/html/autoexec.sh
        
